// Initial migration for ocfb_business schema.
// Tables: baas_tenant, baas_device_template, baas_device,
// baas_publish, baas_bot_run_queue.
//
// Apply with: dotnet ef database update
// Prerequisites: PostgreSQL must have the ocfb_business schema
// created and the connection user must have USAGE + CREATE privileges.

// Note: This migration file serves as documentation of the expected
// DDL. Actual EF Core migration is generated by:
//   dotnet ef migrations add InitialOcbBusiness
// EF Core migration pending database availability.
