<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Sdk">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Orleans.Runtime" />
    <PackageReference Include="Microsoft.Orleans.Persistence.AdoNet" />
    <PackageReference Include="Microsoft.Orleans.Streaming" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ocb.Contracts\Ocb.Contracts.csproj" />
    <ProjectReference Include="..\Ocb.GrainContracts\Ocb.GrainContracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Ocb.Grains.Tests" />
  </ItemGroup>

</Project>
